language: node_js
node_js:
  - 8
sudo: false
dist: trusty
addons:
  chrome: stable
cache: yarn
env:
  global:
    - JOBS=1
    # npm (ZYtF)
    - secure: ZYtFfhPoZX+TVkGicbLaWmeL1btgHaY8BZj+IuEMFJJuCft0Q0ixOxFZ/e/9GjLfEZp0wjNSjE1TgQmJagH4V0Tis7cGD2Gv2V4ZHMgvR7UI9Ktwa+s4HYZs2Q6rhTHsXWG9EJ6cFW74x3Kjly8a49RoG4tXGeaZBjq3ANgTuLF6gBHTSTtSzwFYcyj2R7csF+1k7xFNf/mFUh+YTtpnUshng54UiYxk/Yz+tOQAYLF0tYlSiMpbwwHc2uwxaoZcJ2J1lkyHsP8nCYM18cLX6CGaueqbAVDNlBEDljgwb4Hnt0omiBOeR9iS/elNEDwAddERav8sIdR0IdGJxKEeg9HzEfSXd8Y0Wh/XB/u86c2WgTKyHW6hidUigVZD3uyudSjBc+ZBwc7zb7dhMWfEozYs1yC9JkiYKyI9TdIu24imqZwE1eCm3+vVVn0Qo/zcFFueUOZNp/cL884hJ4iRV4ed65PacVWzsf1/Q5ThiYYi2XRgNW9q1RR1V51BGQx2zEeBnnP4rwGzfExXHyLmsN76uTTUMONRoxAPIMfrAK0EQfiCTi6hfk7JgqUsgS3sdNbLTDcvqwtq0K09CRCnT51iUqZqlohH8QVMtv9SaWIKVpPHV1BICfxMdXIpdc4dmNKnEmYXNtUTfWRNb4EzVCA2j77T6emDrNZBwgHbHJY=
    # gh (eGrT)
    - secure: eGrTwm1/MnMC7t+WRCjnN0+I6WwlUY+CA1hHf+sb530kAvsydg1yTRtCCqraPlAeEBpUko3fsMYsHE2sdw8AXh5s+SP+epTHApIhft+vWXWKvZO+R4sImy3SeUAIVnoiripA1+MHlOXb8DQTJwX2O9x16iM2/r001mRT72wQrrj4clRLpxwxVJfFY3h4qSithnim8642eF3Kl9ENn7GKFu/JJBvw+xLySjus5iKx7fUyF7mCFERHW4U3MWNq5t3pFgx22qmWjPtoYt/WtKGzniAqO55sODKrUdMlLgvSw1sUv1v1ksha+yF/b3utvP9+eZmqE77x6M7xqawuyaUyHm334W+NQTHLFIzHiGP1IPbMFy7N+UDDxfyGy4hqN+hRwfG+jAIHznlGFeO0X25P4XdS2fkJN3UIX/vHUnU79JLne/kYolX3i8x29duStccZGsSIwPuGTeleAvcX8tvPeG30T7EGksIsCpt0yorDaEVCj/EaDQCLIAA3BkWhgCv81eDLVjhcBMdX7seoFEVB4R6w2Ld7RlFwlYM7TFQ0FCoca/Y058E+i5iX6qLTv9PykoUvl9zohRo7Ea8C7fDUFuceuSLfxSSz5qUJb774Tyd1u3WZutucHv6z3zNp0HSU6sPTf+AA0ZOfzOtmRIVBbay77kWpPH7gweIBQj7h2bs=

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=typescript-beta
    - env: EMBER_TRY_SCENARIO=ember-cli-beta
  include:
    # Scenario: obey lockfile
    - stage: 'Tests @ Locked Dependencies'
      name: 'Tests @ Locked Dependencies'
      install:
        - yarn install --non-interactive # omitted usual --no-lockfile
      script:
        - test $MD_ONLY && echo "Skipped! 'yarn lint:js'"    || yarn lint:js
        - test $MD_ONLY && echo "Skipped! 'yarn ci:prepare'" || yarn ci:prepare
        - test $MD_ONLY && echo "Skipped! 'yarn ci:test'"    || yarn ci:test

    # Scenario: lockfile deleted & re-created
    - name: 'Floating Dependencies'
      script:
        - test $MD_ONLY && echo "Skipped! 'yarn ci:prepare'" || yarn ci:prepare
        - test $MD_ONLY && echo "Skipped! 'yarn ci:test'"    || yarn ci:test

    - stage: 'Supported TypeScript & Ember-CLI Versions'
      env: EMBER_TRY_SCENARIO=typescript-release
    - env: EMBER_TRY_SCENARIO=typescript-beta
    - env: EMBER_TRY_SCENARIO=ember-cli-release
      node_js: 10 # slightly more modern node, so travis-deploy-once selects this job for publish
      script:
        - test $MD_ONLY && echo "Skipped!" || yarn ci:prepare
        - test $MD_ONLY && echo "Skipped!" || yarn ember try:one $EMBER_TRY_SCENARIO && yarn travis-deploy-once "yarn semantic-release"
    - env: EMBER_TRY_SCENARIO=ember-cli-beta

    # Scenario: Things we keep an eye on, but do not technically support.
    #           This stuff should align with jobs->allow_failures above
    - stage: 'Canary & Beta Tests (allowed to fail)'
      script:
        - test $MD_ONLY && echo "Skipped! 'yarn ci:prepare'" || yarn ci:prepare
        - test $MD_ONLY && echo "Skipped! 'yarn ci:test'"    || yarn ci:test
      env: EMBER_TRY_SCENARIO=typescript-beta
    - env: EMBER_TRY_SCENARIO=ember-cli-beta
before_install:
  - bash ./is_md_only.sh && MD_ONLY=true && echo "Only .md files have changed!" || test true
install:
  - test $MD_ONLY && echo "Skipped!" || yarn install --no-lockfile --non-interactive
script:
  - test $MD_ONLY && echo "Skipped!" || yarn ci:prepare
  - test $MD_ONLY && echo "Skipped!" || yarn ember try:one $EMBER_TRY_SCENARIO --skip-cleanup && yarn travis-deploy-once "yarn semantic-release"
branches:
  only:
    - master
